include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/*.mock.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
linter:

  rules:
    prefer_relative_imports: true
    always_use_package_imports: false
    use_build_context_synchronously: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: true
    require_trailing_commas: false
    one_member_abstracts: false
    avoid_dynamic_calls: false
    omit_local_variable_types: false
